import time

print("Depois de chegar em casa de um longo dia")
time.sleep(2)
print("Recebi um tema na escola, mas um novo jogo lançou...")
time.sleep(2)
choice1 = input("1 - Fazer o tema ou 2 - jogo o novo lançamento?")

if(choice1 == "1"):
    print("Acabei tema, já está tarde, irei dormir?")
    time.sleep(2)
    print("Ou será que ainda dá tempo de jogar o lançamento?")
    choice2 = (input("1 - dormir agora ou 2 - jogar o novo lançamento"))
    if(choice2 == "1"):
        print("Ótimo, já estava com sono.")
        time.sleep(1)
        print("*Noite passou* Acordei na hora certa, posso ir ao colégio agora.")
        time.sleep(1)
        print("Chegando à aula o professor recolhe o trabalho e dá a nota, você passou!")
        time.sleep(2)
        choice3 = input("Depois dá aula poderei: 1 - voltar à pé ou 2 - voltar de carro")
        if(choice3 == "1"):
            print("O caminho estava traquilo...")
            time.sleep(2)
            print("Você chegou em casa e almoçou um Strogonoff de Frango")
            time.sleep(2)
            print("FIM")
        elif(choice3 == "2"):
            print("No meio do caminho o carro bateu no Posto Ipiranga")
            time.sleep(2)
            print("A gasolina vazou...")
            time.sleep(2)
            print("O Posto Ipiranga explodiu!")
            time.sleep(2)
            print("FIM")
    elif(choice2 == "2"):
        print("Baita jogo")
        time.sleep(1)
        print("Só preciso acordar a tempo da aula amanhã")
        time.sleep(1.5)
        print("*Chegando na aula* o professor começa a recolher os trabalhos")
        time.sleep(2)
        print("Você passou de ano!")
        time.sleep(2)
        print("FIM")
elif(choice1 == "2"):
    print("Baita jogo, amanhã eu faço o trabalho da escola.")
    time.sleep(1)
    print("*Noite passa* Acordei na hora certa para ir a escola")
    time.sleep(1)
    print("Chegando na escola o professor começa a recolher os trabalhos...")
    time.sleep(2)
    print("Você pegou recuperação no trimestre!")
    time.sleep(2)
    print("FIM")